baseurl = "https://www.creekorful.org"
languageCode = "en-us"
theme = "hello-friend-ng-clone"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you linke
enableSharingButtons = true

# Metadata used in document's HEAD
description = "My new homepage or blog"
keywords = "homepage, blog"

copyright = "Aloïs Micard"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/creekorful"

[[params.social]]
name = "debian"
url = "https://qa.debian.org/developer.php?login=alois%40micard.lu&comaint=yes"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/creekorful"

[[params.social]]
name = "telegram"
url = "https://t.me/creekorful"

[[params.social]]
name = "matrix"
url = "https://matrix.to/#/@creekorful:matrix.org"

[languages]
[languages.en]
title = "Aloïs Micard"
subtitle = "Architecture & security"
homeSubtitle = "Architecture & Security | Open Source | Debian Developer"

[languages.en.params.logo]
logoText = "$ /home/"
logoHomeLink = "/"
logoCursorColor = "#67a2c9"

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "https://resume.creekorful.dev"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://blog.creekorful.org"

[params.portrait]
path     = "/img/avatar.jpg"
alt      = "Portrait"

[params.footer]
trademark = true
rss       = false
copyright = true
author    = false

topText = []
bottomText = [
  "<a style=\"text-decoration: none\" href=\"mailto:alois@micard.lu\">alois@micard.lu</a> / <a style=\"text-decoration: none\" href=\"mailto:creekorful@debian.org\">creekorful@debian.org</a>"
]
