baseurl = "https://www.creekorful.org"
languageCode = "en-us"
theme = "hello-friend-ng-clone"

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you linke
enableSharingButtons = true

# Metadata used in document's HEAD
description = "My new homepage or blog"
keywords = "homepage, blog"

# Default theme "light" or "dark"
defaultTheme = "dark"

# Social icons
[[params.social]]
name = "github"
url = "https://github.com/creekorful"

[[params.social]]
name = "debian"
url = "https://qa.debian.org/developer.php?login=alois%40micard.lu&comaint=yes"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/creekorful"

[[params.social]]
name = "telegram"
url = "https://t.me/creekorful"

[[params.social]]
name = "matrix"
url = "https://matrix.to/#/@creekorful:matrix.org"

[[params.social]]
name = "email"
url = "mailto:alois@micard.lu"

[languages]
[languages.en]
title = "Aloïs Micard"
subtitle = "Architecture & security"
homeSubtitle = "Architecture & Security | Open Source | Debian Developer"

[languages.en.params.logo]
logoText = "$ /home/"
logoHomeLink = "/"
logoCursorColor = "#67a2c9"

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "https://resume.creekorful.dev"

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "https://blog.creekorful.org"
